version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: telegram-bot-db-container
    environment:
      POSTGRES_DB: telegramdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - telegram-bot-pgdata:/var/lib/postgresql/data

volumes:
  telegram-bot-pgdata: